server:
  port: 8085
spring:
  application:
    name: trade-service # ????
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hm-trade?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 192.168.150.102
    port: 6379
    database: 0
    timeout: 3000ms
  cloud:
    nacos:
      server-addr: 192.168.150.102 # nacos??
seckill:
  async:
    rocketmq:
      name-server: 192.168.150.102:9876
      request-topic: seckill_request_topic
      request-tag: seckill_request
      request-producer-group: trade-seckill-request-producer-group
      request-consumer-group: trade-seckill-request-consumer-group
      order-topic: seckill_order_topic
      order-tag: seckill_order
      order-producer-group: trade-seckill-order-producer-group
      order-consumer-group: trade-seckill-order-consumer-group
    redis:
      stock-key-prefix: "seckill:stock:"
      users-key-prefix: "seckill:users:"
    token-bucket:
      permits-per-second: 200
      burst-capacity: 200
    websocket:
      endpoint: /ws/seckill
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
knife4j:
  enable: true
  openapi:
    title: ????????
    description: "??"
    email: zhanghuyi@itcast.cn
    concat: ??
    url: https://www.itcast.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.hmall.trade.controller
